### ISSUE TITLE
Not working with Ajax call

### ISSUE THREAD

**Issue by ghost** [Satsume/CKEditorModule#3]
When a form is created inside an Ajax call, the second time the control is not replaced because the CKEDITOR is created on the global script.

When you are rendering  the script in FormCKEditor,php, you shoud call the load function everytime.

If ckEditorLoading is define, clear the ckEditorCallbacks array.
Push the load function every time.
Put the calls of ckEditorCallbacks outside the ckEditorLoading condition.

Thanks

**Comment by JaapMoolenaar** [comment]
I see what you're saying.
Basically the script loads only the editors available in the first (html) load.

Forms loaded added via ajax also include the `<script>` part, which can be used to load dynamically added editors. I believe executing the load function when `if(typeof CKEDITOR == "undefined"){` evaluates as false would do the trick.

I'll push a fix to the development branch.

**Comment by JaapMoolenaar** [comment]
When able, please test the development branch.

**Comment by ghost** [comment]
I replied you this morning, but my message is not there.

Your fix is working fine.

However my needs are more complicated. 

I'm using tokens that may change. Just loading it again is not enough. 

Here's my fix

[FormCKEditor.zip](https://github.com/Satsume/CKEditorModule/files/105840/FormCKEditor.zip)
. 
I also added support for Extra plugins. Feel free to use it if you want to.

The syntax is:

CKeditor options:

'extraPlugins' => 'token',

'ckeditor_external_plugins' => array(
    array('name'=>'token', 'folder' => '/js/plugins/token/', 'filename' => 'plugin.js'),
)

I have another minor issue:

When using your module with twb-bundle, this one is not working anymore because both are extending FormElement and your one is bypassing the other.

My fix is disabling your definition in Module.config and added these lines to my form:

$viewRender = $this->getServiceLocator()->getServiceLocator()->get('ViewRenderer');  
$viewRender->plugin('form_element')->addType('ckeditor', 'formckeditor');

I'm sure there are a better solution, but I'm not an expert of ZF2.

Thanks
